### PR TITLE
Fix windows tests

### LINKED ISSUE #124: Unstable test
Even if my pull request was green, the merge into master left one test failing.

> Test 'PhpPact\Standalone\Runner\ProcessRunnerTest::testBlockingProcess' started
> [2019-05-30 02:54:05] server.DEBUG: Process command: dir  [] []
> [2019-05-30 02:54:05] server.DEBUG: Exit code: 0 [] []
> [2019-05-30 02:54:05] server.DEBUG: Process command: dir failed.xx [] []
> [2019-05-30 02:54:05] server.DEBUG: Exit code: 2 [] []
> Test 'PhpPact\Standalone\Runner\ProcessRunnerTest::testBlockingProcess' ended
> 
> There was 1 failure:
> 
> 1) PhpPact\Standalone\Runner\ProcessRunnerTest::testBlockingProcess
> Expect 'failed.xx' to be in the stderr
> Failed asserting that false is true.
> C:\projects\pact-php\tests\PhpPact\Standalone\Runner\ProcessRunnerTest.php:47

Any ideas how to fix it?

### PR DESCRIPTION
**Pull request by Thomblin**
simplifies ProcessRunner:stop in order to make it work properly on windows systems

fixes #124

### CODE REVIEW

File: src/PhpPact/Standalone/Runner/ProcessRunner.php [hunk 1]
```diff
@@ -193,27 +193,17 @@ public function run($blocking = false): int
...
-                throw new ProcessException(\sprintf('Unable to kill the process (%s).', \implode(' ', $output)));
-            }
+            \exec(\sprintf('taskkill /F /T /PID %d 2>&1', $pid), $output, $exitCode);
         }
 
         $this->process->kill();
 
-        if ($this->process->isRunning()) {
-            throw new ProcessException(\sprintf('Error while killing process "%s".', $pid));
-        }
```
Comment (cfmack) [inline src/PhpPact/Standalone/Runner/ProcessRunner.php]: Does removing this validation simply high non-killed processes?

Comment (Thomblin) [reply src/PhpPact/Standalone/Runner/ProcessRunner.php]: You are right. I readded it and it seems to work fine.

**Comment by cfmack** [comment]
Let's give this a shot!
